name: ci-golang-workflow
on:
  pull_request:
    branches:
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     go: ["1.14", "1.15"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          # go-version: ${{ matrix.go }}
          go-version: 1.18
      - run: go test
      - run: go run math.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: sidartaoss/fc2.0-ci-go:latest
